// Loads the full flow/suite catalog generated by scripts/build-catalog.mjs
// from the fluxproto-light binary. Fetched at runtime (the catalog page is a
// lazy route, so this never costs the initial bundle).

export interface CatalogFlow {
  name: string;
  source: string;
  type: string;
  protocol: string;
  nf: string;
  category: string;
  description: string;
  path: string;
}

export interface CatalogSuite {
  name: string;
  source: string;
  steps: number;
  description: string;
  path: string;
}

export interface Catalog {
  generatedAt: string;
  repoUrl: string;
  totals: { flows: number; suites: number };
  byProtocol: Record<string, number>;
  byNf: Record<string, number>;
  byCategory: Record<string, number>;
  flows: CatalogFlow[];
  suites: CatalogSuite[];
}

let cached: Promise<Catalog> | null = null;

export function getCatalog(): Promise<Catalog> {
  if (!cached) {
    cached = fetch('/catalog.json', { cache: 'force-cache' }).then((r) => {
      if (!r.ok) throw new Error(`catalog: HTTP ${r.status}`);
      return r.json() as Promise<Catalog>;
    });
  }
  return cached;
}

// GitHub blob URL for a flow/suite YAML in the (public) templates repo.
export function sourceUrl(repoUrl: string, path: string): string {
  return `${repoUrl}/blob/main/${path}`;
}
