// Loads a CLI reference generated by scripts/build-cli.mjs from a binary's
// --help output. Fetched at runtime (CLI pages are lazy routes).

export interface CliItem {
  syntax: string;
  desc: string;
}
export interface CliSection {
  title: string;
  items: CliItem[];
}
export interface CliDoc {
  generatedAt: string;
  name: string;
  tagline: string;
  usage: string[];
  sections: CliSection[];
  examples: string[];
}

const cache: Record<string, Promise<CliDoc>> = {};

export function getCli(key: string): Promise<CliDoc> {
  if (!cache[key]) {
    cache[key] = fetch(`/cli-${key}.json`, { cache: 'force-cache' }).then((r) => {
      if (!r.ok) throw new Error(`cli-${key}: HTTP ${r.status}`);
      return r.json() as Promise<CliDoc>;
    });
  }
  return cache[key];
}
