// Generates public/cli-<name>.json + src/generated/cliMeta.ts from the
// fluxproto-light binary's `--help` output, so the CLI references can't drift.
//
// Runs LOCALLY; if a binary is missing it skips that one and keeps the committed
// JSON, so CI/Vercel builds stay green. Regenerate with:  npm run build:cli
//
// Override the binary dir with FPL_BIN_DIR=/path/to/fluxgate-proxy/bin

import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BIN_DIR = process.env.FPL_BIN_DIR || resolve(root, '../fluxproto-light/bin');

// Each entry → one CLI reference page's data.
const CONFIG = [
  { key: 'cli', bin: 'fluxproto-light', argv: ['--help'] },
];

// Parse a `--help` text into { name, tagline, usage[], sections[{title, items[{syntax, desc}]}], examples[] }.
function parseHelp(text) {
  const lines = text.replace(/\r/g, '').split('\n');
  const out = { name: '', tagline: '', usage: [], sections: [], examples: [] };
  let cur = null; // current section
  let mode = ''; // '', 'usage', 'examples'

  for (const raw of lines) {
    const line = raw.replace(/\s+$/, '');
    if (line.trim() === '') continue;

    // "name - tagline" header.
    const head = line.match(/^(\S+)\s+-\s+(.+)$/);
    if (!out.name && head) {
      out.name = head[1];
      out.tagline = head[2];
      continue;
    }

    // Section headers: a non-indented line ending with ':'.
    const header = line.match(/^(\S.*):\s*$/);
    if (header && !line.startsWith(' ')) {
      const title = header[1];
      if (/^usage/i.test(title)) { mode = 'usage'; cur = null; continue; }
      if (/^examples/i.test(title)) { mode = 'examples'; cur = null; continue; }
      mode = '';
      cur = { title, items: [] };
      out.sections.push(cur);
      continue;
    }

    // Indented content.
    if (/^\s/.test(line)) {
      const body = line.trim();
      if (mode === 'usage') { out.usage.push(body); continue; }
      if (mode === 'examples') { out.examples.push(body); continue; }
      if (cur) {
        // "  <syntax>   <description>" — split on the first run of 2+ spaces.
        const m = line.match(/^\s+(\S.*?)\s{2,}(.+)$/);
        if (m) cur.items.push({ syntax: m[1].trim(), desc: m[2].trim() });
        else cur.items.push({ syntax: body, desc: '' });
      }
      continue;
    }
  }
  // Drop empty sections.
  out.sections = out.sections.filter((s) => s.items.length > 0);
  return out;
}

const generatedAt = new Date().toISOString().slice(0, 10);
const built = [];

for (const c of CONFIG) {
  const binPath = join(BIN_DIR, c.bin);
  if (!existsSync(binPath)) {
    console.warn(`[build-cli] ${binPath} not found — keeping committed public/cli-${c.key}.json`);
    continue;
  }
  let text;
  try {
    text = execFileSync(binPath, c.argv, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (e) {
    // Many CLIs print help to stderr and exit non-zero.
    text = e.stdout || e.stderr || '';
  }
  const data = { generatedAt, ...parseHelp(text) };
  const out = resolve(root, `public/cli-${c.key}.json`);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, JSON.stringify(data, null, 2) + '\n');
  built.push({ key: c.key, name: data.name, sections: data.sections.length });
  console.log(`[build-cli] wrote public/cli-${c.key}.json (${data.sections.length} sections)`);
}

// Tiny meta module so pages know which keys generated successfully + the date.
mkdirSync(resolve(root, 'src/generated'), { recursive: true });
writeFileSync(
  resolve(root, 'src/generated/cliMeta.ts'),
  '// AUTO-GENERATED by scripts/build-cli.mjs — do not edit by hand.\n' +
    `export const cliGeneratedAt = '${generatedAt}';\n`,
);
